### PR TITLE
Added Image Picking Functionality

### PR DESCRIPTION
**Pull request by DominatorVbN**
No breaking changes in API
Removed sampleData (didn't required it anymore)

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! Thank you for this. What happens if someone doesn't have a QR code in their simulator photo library?

**Comment by DominatorVbN** [comment]
I think sample data should be there and we can provide a button to mock the scan or pick from the gallery.

**Comment by twostraws** [comment]
Well, if you could please provide a solution that preserves backward compatibility that would be great. This library is used in my videos (see https://www.hackingwithswift.com/books/ios-swiftui/scanning-qr-codes-with-swiftui), so I want to make sure folks can continue using it without having to have a QR code in their library.

**Comment by DominatorVbN** [comment]
I had updated the codebase with backward compatibility with sampleData users can optionally provide sample data.
If they provide the samapleData they will be shown with an extra button "Mock scan with sample data", otherwise only with pick image from the gallery button.

**Comment by DominatorVbN** [comment]
> Well, if you could please provide a solution that preserves backward compatibility that would be great. This library is used in my videos (see https://www.hackingwithswift.com/books/ios-swiftui/scanning-qr-codes-with-swiftui), so I want to make sure folks can continue using it without having to have a QR code in their library.

I am also learning from your content thanks for putting the vast contents for us.

**Comment by twostraws** [comment]
Thank you!

**Pull request merged**
