### PR TITLE
fixes #72 Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### LINKED ISSUE #72: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
The app crashes with this testing it in a physical device. The error comes in the ScannerViewController while passing the session as a parameter.

### PR DESCRIPTION
**Pull request by uniqby**

### CODE REVIEW

**Comment by odariusgeorge** [comment]
@twostraws can this be merged?

**Comment by twostraws** [comment]
Yes – thank you!

**Comment by dramikei** [comment]
This fixes #68 FYI

**Comment by ian-sayles** [comment]
I keep getting something similar when user first runs app and is asked to give  permission to access the camera.
It crashes with the following error, this happens before the 'OK' button is pressed, if press the button, when start the app again it works fine.

CodeScanner/ScannerViewController.swift:178: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2022-08-12 09:30:14.185667+0100 [405:12472] CodeScanner/ScannerViewController.swift:178: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

if previewLayer == nil {
      previewLayer = AVCaptureVideoPreviewLayer(session: captureSession)
}

The version of Codescanner 2.1.2 and iOS 15.6

**Comment by NathanFallet** [comment]
@twostraws Can you tag a new version (eg: 2.1.3) with this fix?

**Pull request merged**
