### PR TITLE
Adding more customization options

### LINKED ISSUE #22: Front Camera
I've looked over everything, and I can’t see a way to use the front camera. I was wondering if I have missed something, and if not, how difficult it would be to implement. I don't have a very in-depth knowledge to Swift, but I have tried to look over some possibilities of how to do it, but achieved nothing

### LINKED ISSUE #50: Add a view modifier to control torch light
Adding an ability to turn on/off torch light.

This snippet can be used:
```swift
    func torch(torchIsOn: Bool) -> CodeScannerView {
        if let backCamera = AVCaptureDevice.default(for: AVMediaType.video) {
            if backCamera.hasTorch {
                try? backCamera.lockForConfiguration()
                backCamera.torchMode = torchIsOn ? .on : .off
                backCamera.unlockForConfiguration()
            }
        }
        return self
    }
```

Note: if I have some free time next week, I will try to make a Pull Request for that

### LINKED ISSUE #51: Add a view modifier to allow to present gallery and import a code
As it can be done in the simulator, add the ability to import an image from gallery and load a qr code from it.

This can be done this way:
```swift
CodeScannerView(
    // ...
)
.importFromGallery(isPresented: $importFromGallery)
```

Where `$importFromGallery` is a `Binding<Bool>`

Note: if I have some free time next week, I will try to make a Pull Request for that

### PR DESCRIPTION
**Pull request by NathanFallet**
In this pull request:
- I added a parameter to control torch light: fixes #50 
- I added a parameter to present gallery (to import a code): fixes #51 
- I added a parameter to choose video capture device: fixes #22

### CODE REVIEW

**Comment by NathanFallet** [comment]
@twostraws The pull request is ready, and should fix #50, #51 and #22 😄
Feel free to review it and merge it when you have time to

**Comment by twostraws** [comment]
Hi Nathan! Thank you for your contribution – it looks great! Can you confirm this doesn't break compatibility with the existing 2.0.0 release?

**Comment by NathanFallet** [comment]
@twostraws I can confirm it does not break anything, as I only added optional arguments with default values.

**Comment by twostraws** [comment]
Thank you!

**Pull request merged**
